apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "pr-demo-1"
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: previews
  source:
    path: helm
    repoURL: valerann.jfrog.io/docker/demo.git
    targetRevision: HEAD
    helm:
      values: |
        image:
          tag: "production"
        ingress:
          host: "pr-demo-1.192.168.5.90.xip.io"
      version: v3
  destination:
    namespace: "pr-demo-1"
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
