apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: admin
spec:
  source:
    path: admin/argocd/production
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: valerann
spec:
  source:
    path: clusters/production/helm
