argo-cd:
  installCRDs: false
  fullnameOverride: "argocd"
  global:
    image:
      tag: v1.8.7
  server:
    config:
      repositories: |
        - type: helm
          name: stable
          url: https://charts.helm.sh/stable
        - type: helm
          name: argo-cd
          url: https://argoproj.github.io/argo-helm
        - type: helm
          name: datawire
          url: https://getambassador.io
        - type: helm
          name: ingress-nginx
          url: https://kubernetes.github.io/ingress-nginx
