argo-cd:
  installCRDs: false
  fullnameOverride: "argocd"
  global:
    image:
      tag: v1.8.7
  server:
    # rbacConfig:
    #   policy.csv: |
    #     # Grant all members of the group 'my-org:team-alpha; the ability to sync apps in 'my-project'
    #     p, my-org:team-alpha, applications, sync, my-project/*, allow
    #     # Grant all members of 'my-org:team-beta' admins
    #     g, my-org:team-beta, role:admin

    config:
      repositories: |
        - type: helm
          name: stable
          url: https://charts.helm.sh/stable
        - type: helm
          name: argo-cd
          url: https://argoproj.github.io/argo-helm
        - type: helm
          name: datawire
          url: https://getambassador.io
        - type: helm
          name: ingress-nginx
          url: https://kubernetes.github.io/ingress-nginx
